# Generated by Django 4.0.2 on 2022-02-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthCredential',
            fields=[
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.TextField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField(primary_key=True, serialize=False)),
                ('scopes', models.URLField(max_length=240)),
            ],
        ),
    ]
