# Generated by Django 4.0.2 on 2022-02-06 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_googleoauthcredential'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googleoauthcredential',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='googleoauthcredential',
            name='token',
        ),
        migrations.RemoveField(
            model_name='googleoauthcredential',
            name='token_uri',
        ),
    ]
